export const FETCH_ORDER_BOOK_STARTED = "FETCH_ORDER_BOOK_STARTED";
export const FETCH_ORDER_BOOK_SUCCEEDED = "FETCH_ORDER_BOOK_SUCCEEDED";
export const FETCH_ORDER_BOOK_FAILED = "FETCH_ORDER_BOOK_FAILED";
