export const FETCH_ORDER_BOOK_STARTED = "FETCH_ORDER_BOOK_STARTED";
export const FETCH_ORDER_BOOK_SUCCEEDED = "FETCH_ORDER_BOOK_SUCCEEDED";
export const FETCH_ORDER_BOOK_FAILED = "FETCH_ORDER_BOOK_FAILED";

export const UPDATE_ORDER_BOOK_ITEM = "UPDATE_ORDER_BOOK_ITEM";

export const INCREMENT_PRECISION = "INCREMENT_PRECISION";
export const DECREMENT_PRECISION = "DECREMENT_PRECISION";
